### ISSUE TITLE
Request reminders access permission explicitly

### ISSUE THREAD

**Issue by f-person** [berkobob/Reminders#1]
Hi! Thank you for this plugin! I just added it to my Flutter app, and as soon as I opened it, the reminders permission was asked. However, this can be pretty confusing for app users. It would be nice if the reminders' access could be requested only manually or when accessing other functions :)

**Comment by berkobob** [comment]
Hi, I'm not in control of when your app requests access to Reminders. I seem to recall from other apps that permissions are always requested on startup. One thing you could try is instantiating the Reminders class only when you want your user to grant permission. I don't know if this will work but it's what I would try.

**Comment by CillianMyles** [comment]
👋 Jumping in since I just read that part of the plugin and I recently implemented this in another project. 

You currently request access during the `init()` block of your `Reminders.swift` class:
https://github.com/berkobob/reminders/blob/main/common/Reminders.swift#L10-L13

You can simply move this into a separate method/function, that can be invoked by calling a method e.g. "connect" / "requestAccess", so that the plugin user/Flutter app developer can decide when to ask the user if they will grant access to the user's reminders.

Hope this help!

**Comment by f-person** [comment]
> One thing you could try is instantiating the Reminders class only when you want your user to grant permission.

It's being requested even without ever importing the package into the Flutter codebase since it's done natively in Swift whenever the plugin is initialized (as @CillianMyles mentioned). The solution offered by @CillianMyles will fix this issue

**Comment by berkobob** [comment]
My concern here is that if I remove the default of requesting access on instantiation then any apps using this package will stop working because they won't have a separate step to request access. Is there a way around this? If not, then I suggest you fork this version and move the request out of `init()` into a separate func.

**Comment by Justus-M** [comment]
> My concern here is that if I remove the default of requesting access on instantiation then any apps using this package will stop working because they won't have a separate step to request access. Is there a way around this? If not, then I suggest you fork this version and move the request out of `init()` into a separate func.

Thanks for creating this package!

You could just have the access request happen when the Reminders() class is instantiated. That way it will be requested by default, but at least the developers using this package still have some level of control as they can wait to instantiate it if they don't want the permission request to happen right away.

It's quite important to be able to control when permission is requested, because if an app does 5 permission requests before the user even gets into the app and understands what they're for, they will probably decline some and then have to go to their settings to manually enable them. It leads to quite a bad UX.

**Comment by berkobob** [comment]
Hi @Justus-M, thanks for your helpful note. I accept your argument and am happy to do this.

 I think the problem is that I'm using the default template for creating a platform interface. The default template creates a singleton which is instantiated straightaway. If I create a new interface which does not use an instantiated singleton then maybe that would work. What do you think? Is there an easier way that ocurs to you?

**Comment by Justus-M** [comment]
> Hi @Justus-M, thanks for your helpful note. I accept your argument and am happy to do this.
> 
> 
> 
>  I think the problem is that I'm using the default template for creating a platform interface. The default template creates a singleton which is instantiated straightaway. If I create a new interface which does not use an instantiated singleton then maybe that would work. What do you think? Is there an easier way that ocurs to you?

@CillianMyles can you jump in here?

**Comment by SethuSenthil** [comment]
Hey guys! I took the time to build out the full implementation based on @CillianMyles 's prospal. I submitted the pull request and it is yet to be merged.  I also updated the dependencies and environment versions incase you were having issues with those. 

You can use this in your project right now as follows in your pubspec.yaml:
```yaml
dependencies:
  flutter:
    sdk: flutter
  reminders:
    git: https://github.com/SethuSenthil/reminders

**Comment by SethuSenthil** [comment]
@berkobob I think you can close this issue now 😄

**Comment by f-person** [comment]
Awesome stuff!
